version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_artifacts:
          path: build/libs/

workflows:
  build:
    jobs:
      - build
